### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by teamcoltra** [dabernathy89/gravity-forms-personality-quiz-add-on#2]
This was on the wordpress forums, but I will add it here too for milestone / tracking sake: 

Please provide documentation. A simple step by step into creating your first quiz would be perfect. You could even do screenshots and make it easy on yourself :)

**Comment by corysimmons** [comment]
:+1: screenshots and maybe a small video.

**Comment by dabernathy89** [comment]
Improved the readme, going to add some screenshots to the repo in WordPress as well.
