### ISSUE TITLE
Shuffle Answers not working

### ISSUE THREAD

**Issue by alexanderritola** [dabernathy89/gravity-forms-personality-quiz-add-on#4]
This might be an issue my end, but I can't figure out what's causing it, and I can't find anything while searching.

The Shuffle Answers option doesn't seem to do anything at all for me.

Also, a feature request: It'd be nice if there was an easy way to randomize the order of the questions (GF Fields). I found [this guide](http://gravitywiz.com/random-fields-with-gravity-forms/) on randomizing gravity forms fields, and I believe I can make this work to suit my needs, the code is a old and seems to throw some warnings, but I'm pretty sure I can make it work. Regardless, just something to consider.

Thanks!

**Comment by cabgfx** [comment]
+1, I couldn't get it working either

**Comment by dabernathy89** [comment]
@alexanderritola sorry, just getting back to this. are you still having this issue? If so, do you have a link? My guess is a jQuery conflict.

**Comment by dabernathy89** [comment]
Closing this out. If someone is able to recreate this, feel free to open a new ticket with some more detail.
