### ISSUE TITLE
Keep question field label visible when using image label

### ISSUE THREAD

**Issue by hannahmwool** [dabernathy89/gravity-forms-personality-quiz-add-on#5]
Hi,

Great plugin! Is there a function on this to keep the question field label when using an image label also instead of replacing it? Like this buzzfeed style http://www.buzzfeed.com/tahliapritchard/how-well-do-you-know-your-australian-music#.diPEL2QYE

Thanks!

**Comment by dabernathy89** [comment]
I believe the label field accepts any HTML, so you should be able to just insert text and then a line break before the <img> element. Let me know if it works!

**Comment by hannahmwool** [comment]
Hi I managed to edit the public function replace_field_labels str_replace. But that's perfect that I can add html in the same field for the image! Why didn't I try that first!

Thanks! 

P.S. I wanted to know if you have any suggestions for sharing the quiz results. I have ShareThis integrated but it doesn't pick up content just the link for the page. I'm thinking of maybe a shortcode for it. I can open this as a new issue (even though its more of a nice feature) to keep it separate. Thanks again!

**Comment by dabernathy89** [comment]
What kind of confirmation are you doing? If you do a redirect instead of text, then it should be pretty simple to be able to share that page content, unless you're using merge tags in the confirmation text.

**Comment by hannahmwool** [comment]
I'm using text confirmations rather than a redirect just to keep it simple for the user as more quizzes are made I'd like to avoid multiple result pages for the redirects. Thanks for the suggestion. 

The user has decided to explore a sharing option in the future. Thank you for your help and fast response and again, great plugin!
